# -*- coding: utf-8 -*-
"""ActivityLab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XSOdw1cpx2PD53tSD5TKRvdMeuME64N
"""

nama = "Saiful Jamil"
umur = 18
ipk = 3.75
mahasiswa_aktif = True

print(nama)
print(umur)
print(ipk)
print(mahasiswa_aktif)

print(type(nama))
print(type(umur))
print(type(ipk))
print(type(mahasiswa_aktif))

print(len(nama))

nilai = 85.5

print(nilai)
print(type(nilai))

nilai_baru = int(nilai)

print(nilai_baru)
print(type(nilai_baru))

skor = 90
skor_teks = str(skor)

print("Nilai saya adalah " + skor_teks)
print(type(skor_teks))
print(type(skor))

berat = "65.5"
berat_baru = float(berat)

print(berat_baru)
print(type(berat_baru))
print(berat_baru + 2.5)